# Generated by Django 3.2.5 on 2021-11-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_folder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
